server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 437f41f7-3c9f-4d28-a58a-4ccc996bc232
    sentinel:
      # 开启对spring mvc端点的保护
      filter:
        enabled: true
      # 配置 sentinel dashboard 地址
      transport:
        dashboard: localhost:8080
      datasource:
        # 集成 Nacos
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            namespace: ${spring.cloud.nacos.discovery.namespace}
            username: nacos
            password: nacos
            data-id: gateway-flow-rule-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
        ds2:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            namespace: ${spring.cloud.nacos.discovery.namespace}
            data-id: gateway-flow-rule-api-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw-api-group

    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: user-center-gateway
          # 访问http://localhost:8840/users/1 -> user-center/users/1
          uri: lb://user-center
          predicates:
            - Path=/user-center/**

        - id: mall-goods-gateway
          uri: lb://mall-goods
          predicates:
            - Path=/mall-goods/**

        - id: mall-cart-gateway
          uri: lb://mall-cart
          predicates:
            - Path=/mall-cart/**

        - id: mall-order-gateway
          uri: lb://mall-order
          predicates:
            - Path=/mall-order/**

  rabbitmq:
    host: zengshen.org
    port: 5672
    username: root
    password: 123456
  zipkin:
    sender:
      type: rabbit  # 默认是 web
    base-url: http://localhost:9411/
    discovery-client-enabled: false

  main:
    allow-bean-definition-overriding: true  # 因为将来会引入很多依赖, 难免有重名的 bean

  redis:
    host: zengshen.org
    port: 6379
    database: 2
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000


# 这个地方独立配置, 是网关的数据, 代码 GatewayConfig.java 中读取被监听
nacos:
  gateway:
    route:
      config:
        data-id: gateway-mall.json
        group: DEFAULT_GROUP



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200  # 最大的连接数
    max-connections-per-route: 50  # 每个路径的最大连接数


