server:
  port: 8091
  servlet:
    context-path: /user-center

spring:
  application:
    name: user-center

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 437f41f7-3c9f-4d28-a58a-4ccc996bc232
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
    sentinel:
      # 开启对spring mvc端点的保护
      filter:
        enabled: true
      # 配置 sentinel dashboard 地址
      transport:
        dashboard: localhost:8080

  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）

  redis:
    host: zengshen.org
    port: 6379
    database: 2
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000


# 整合 mybatis
# tkMapper这个必须添加不然报错了
mybatis:
  type-aliases-package: com.zengshen.usercenter.model       # 所有实体类类所在的包路径
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl   # 打印sql语句


  rabbitmq:
    host: zengshen.org
    port: 5672
    username: root
    password: 123456
  zipkin:
    sender:
      type: rabbit  # 默认是 web
    base-url: http://localhost:9411/
    discovery-client-enabled: false


